// <auto-generated />
using CRUD_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_Management_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250217104821_CRUDSystemMVC")]
    partial class CRUDSystemMVC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CRUD_Management_System.Models.UserLoginModel", b =>
                {
                    b.Property<string>("AliasId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OnlineStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TheOne")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("AliasId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
